# ==============================================================
# DATOS DEL EQUIPO  (completar ANTES del primer commit de trabajo)
# Escriban nombre y apellido tal cual aparecen en lista.
# ==============================================================
integrante1.nombre=Alexander
integrante1.apellido=Garriga
integrante1.cedula=8-1042-1256

integrante2.nombre=Luis
integrante2.apellido=Zhong
integrante2.cedula=8-1066-834

# VERSION: sumen TODOS los digitos de las dos cedulas (ignoren letras y guiones).
#   suma PAR   -> version=A
#   suma IMPAR -> version=B
# Ejemplo: 8-123-456 y 4-777-100  -> 8+1+2+3+4+5+6 + 4+7+7+7+1+0+0 = 55 -> impar -> B
version=B
